version: '3.1'

services: 
 
  db: 
    container_name : postgres
    image: postgres 
    restart: always
    ports:
      - 5432:5432 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB : postgres 

  adminer:
    container_name: admin
    image: adminer 
    restart: always 
    depends_on: 
       - db 
    ports:
      - 9090:8080

  app:
    container_name: frontend
    image: sotobotero/udemy-devops:0.0.1
    ports:
      - 80:80
      - 8080:8080
    restart: always
    depends_on:
      - db
      - adminer
    

