version: '3.1'

services:

  mongo:
    container_name: mongoDB
    image: mongo
    restart: always
    ports:
      - 27017:85
    volumes:
      - data_bd:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: /run/secrete/db_user
      MONGO_INITDB_ROOT_PASSWORD: example
    secrets:
       - db_user

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: /run/secrete/db_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
    secrets:
       - db_user

secrets:
   db_user:
     file: db_user.txt
volumes:
  data_bd: